server:
  port: 8080

endpoints:
  actuator:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false

spring:
  application:
    name: thrift-calculator-client
  cloud:
    consul:
      host: 192.168.91.128
      port: 8500
      discovery:
        register: false
        register-health-check: true
        health-check-interval: 30s
      retry:
        max-attempts: 3
        max-interval: 2000
  thrift:
    client:
      package-to-scan: com.icekredit.rpc.thrift.example.rpc
      service-model: hsHa
      pool:
        retry-times: 3
        pool-max-total-per-key: 200
        pool-min-idle-per-key: 10
        pool-max-idle-per-key: 40
        pool-max-wait: 1000
        connect-timeout: 2000